package com.company.libros.modelos;
// Generated 01-13-2022 02:02:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,schema="public"
)
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nombre;
     private boolean estado;
     private Set libros = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria, String nombre, boolean estado) {
        this.idCategoria = idCategoria;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Categoria(int idCategoria, String nombre, boolean estado, Set libros) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.estado = estado;
       this.libros = libros;
    }
   
     @Id 

    
    @Column(name="id_categoria", unique=true, nullable=false)
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set libros) {
        this.libros = libros;
    }




}


