package com.company.libros.modelos;
// Generated 01-13-2022 02:02:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name="libro"
    ,schema="public"
)
public class Libro  implements java.io.Serializable {


     private int idLibro;
     private Autor autor;
     private Categoria categoria;
     private BigDecimal precio;

    public Libro() {
    }

    public Libro(int idLibro, Autor autor, Categoria categoria, BigDecimal precio) {
       this.idLibro = idLibro;
       this.autor = autor;
       this.categoria = categoria;
       this.precio = precio;
    }
   
     @Id 

    
    @Column(name="id_libro", unique=true, nullable=false)
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_autor", nullable=false)
    public Autor getAutor() {
        return this.autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_categoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="precio", nullable=false, precision=10)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


